version: 0.0
os: linux
files:
  - source: /InstagramAPIScript/
    destination: /home/ubuntu/PrivateAPI/
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: scripts/clear_dir
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu
